### PR TITLE
Add fr_FR translation

### PR DESCRIPTION
**Pull request by tbnv**

### CODE REVIEW

**Comment by tbnv** [comment]
@atwellpub Thanks for the merge.

It's weird though, the translation is not applied.
I see this in Loco Translate:

> Additional files found
> This bundle isn't fully configured, so we don't know what the following files are for.

And this

> This bundle's configuration has been automatically detected, but isn't fully complete.
>  4 files can't be matched to a known set of strings

**Comment by atwellpub** [comment]
Good eye. Looks like because the plugin is loaded in `init` the text domain isn't loaded. I tried to change the hook level the plugin loaded at to be before `init` but it broke the email send. I pulled the text-domain loader method outside of the plugin class and it's working now.

**Comment by atwellpub** [comment]
If you want to add your WordPress.org username to the readme.txt's contributor list, I'll accept the pull request. It may be fun to have it there.

**Comment by tbnv** [comment]
I added myself to the readme, thanks!

**Pull request merged**
